project_name: "lesion_aware_dr"
run_name: "efficientnet_cb_focal_multidata_v1"

paths:
  data_dir: "/kaggle/working"
  raw_dir: "/kaggle/working"
  processed_dir: "/kaggle/working/multidata_splits"
  outputs_dir: "/kaggle/working/outputs"
  checkpoints_dir: "/kaggle/working/outputs/checkpoints"

model:
  backbone: "efficientnet_b0"
  num_classes: 5
  pretrained: true

data:
  use_dummy: false
  image_size: 224

  # --------------------------------------------------
  # Current training inputs (used by datamodule/train)
  # --------------------------------------------------
  train_csv: "/kaggle/working/multidata_splits/combined_train.csv"
  val_csv: "/kaggle/working/multidata_splits/combined_val.csv"

  # External evaluation input
  test_csv: "/kaggle/working/multidata_splits/messidor2_test.csv"

  # Loader config
  image_dir: ""
  image_col: "image_path"
  label_col: "label"
  dataset_col: "dataset"

  # Sampler
  use_weighted_sampler: false
  sampler_mode: "inverse"

  # --------------------------------------------------
  # Raw dataset sources for split-building script
  # --------------------------------------------------
  sources:
    eyepacs:
      labels_csv: "/kaggle/input/datasets/mohlamin/resized-eyepacs-diabetic-retinopathy-dataset/original_train_labels.csv"
      images_dir: "/kaggle/input/datasets/mohlamin/resized-eyepacs-diabetic-retinopathy-dataset/Images"
      image_ext: ".png"
      image_col_raw: "image"
      label_col_raw: "level"

    aptos:
      root_dir: "/kaggle/input/datasets/mariaherrerot/aptos2019"
      train_csv: "/kaggle/input/datasets/mariaherrerot/aptos2019/train_1.csv"
      val_csv: "/kaggle/input/datasets/mariaherrerot/aptos2019/valid.csv"
      train_images_dir: "/kaggle/input/datasets/mariaherrerot/aptos2019/train_images/train_images"
      val_images_dir: "/kaggle/input/datasets/mariaherrerot/aptos2019/val_images/val_images"
      image_ext: ".png"
      image_col_raw: "id_code"
      label_col_raw: "diagnosis"

    idrid:
      train_csv: "/kaggle/input/datasets/abdullahshafi315/indian-diabetic-retinopathy-image-datasetidrid/Disease Grading/2. Groundtruths/a. IDRiD_Disease Grading_Training Labels.csv"
      test_csv: "/kaggle/input/datasets/abdullahshafi315/indian-diabetic-retinopathy-image-datasetidrid/Disease Grading/2. Groundtruths/b. IDRiD_Disease Grading_Testing Labels.csv"
      train_images_dir: "/kaggle/input/datasets/abdullahshafi315/indian-diabetic-retinopathy-image-datasetidrid/Disease Grading/1. Original Images/a. Training Set"
      test_images_dir: "/kaggle/input/datasets/abdullahshafi315/indian-diabetic-retinopathy-image-datasetidrid/Disease Grading/1. Original Images/b. Testing Set"
      image_ext: ".jpg"
      image_col_raw: "Image name"
      label_col_raw: "Retinopathy grade"

    messidor2:
      labels_csv: "/kaggle/input/datasets/mariaherrerot/messidor2preprocess/messidor_data.csv"
      images_dir: "/kaggle/input/datasets/mariaherrerot/messidor2preprocess/messidor-2/messidor-2/preprocess"
      image_col_raw: "id_code"
      label_col_raw: "diagnosis"
      gradable_col_raw: "adjudicated_gradable"

  # --------------------------------------------------
  # Split-building options
  # --------------------------------------------------
  split:
    random_state: 42
    eyepacs_val_size: 0.2
    idrid_val_size: 0.2
    verify_files: true

    outputs:
      eyepacs_train_csv: "/kaggle/working/multidata_splits/eyepacs_train.csv"
      eyepacs_val_csv: "/kaggle/working/multidata_splits/eyepacs_val.csv"

      aptos_train_csv: "/kaggle/working/multidata_splits/aptos_train.csv"
      aptos_val_csv: "/kaggle/working/multidata_splits/aptos_val.csv"

      idrid_train_csv: "/kaggle/working/multidata_splits/idrid_train.csv"
      idrid_val_csv: "/kaggle/working/multidata_splits/idrid_val.csv"

      combined_train_csv: "/kaggle/working/multidata_splits/combined_train.csv"
      combined_val_csv: "/kaggle/working/multidata_splits/combined_val.csv"

      messidor2_test_csv: "/kaggle/working/multidata_splits/messidor2_test.csv"

training:
  seed: 42
  epochs: 12
  batch_size: 16
  num_workers: 2
  lr: 1e-4
  weight_decay: 1e-5
  optimizer: "adamw"
  scheduler: "cosine"

logging:
  use_wandb: false
  wandb_project: "lesion_aware_dr"
  wandb_entity: null

loss:
  name: "cb_focal"
  beta: 0.999
  gamma: 2.0
  alpha_mode: "effective"
  reduction: "mean"
  use_class_weights: false